### ISSUE TITLE
Stream connection error while using rabbitmq and docker on remote server

### ISSUE THREAD

**Issue by gblessas** [qweeze/rstream#191] opened 2024-04-26 12:30 UTC
Hi,
I'm trying to consume stream with stream protocol using rstream and can't get it work.
Actually i consume it with amqp 0.9 and it's ok.
my version is 3.12.12.
My rabbitmq server is installed as a docker image and not replicated on a remote server. It has stream plugin activated and 5552 port opened. I tried examples for consuming the stream from rstream repository but get "addr resolve issue (joined logs).
If i change user /passwords with wrong ones i get authentication issue.
[script.log](https://github.com/qweeze/rstream/files/15130638/script.log)

[program.py.txt](https://github.com/qweeze/rstream/files/15130632/program.py.txt)

**Comment by DanielePalaia** [comment] 2024-05-03 08:46
HI @gblessas is the suggestion provided by Gabriele working for you? I suspect this to be a duplicate of https://github.com/qweeze/rstream/issues/130. If it is the case I will close this one

**Comment by DanielePalaia** [comment] 2024-05-17 09:34
I will close this one as no further news from the user

**Closed by DanielePalaia** 2024-05-17 09:34 UTC
