### ISSUE TITLE
NotImplementedError in basic_consumers /basic_consumer.py

### ISSUE THREAD

**Issue by Utsavv** [qweeze/rstream#150] opened 2023-11-10 06:31 UTC
Hi,

I am new to python so I might be missing something obvious. However, when I am trying to run [basic_consumers]
/basic_consumer.py, I am getting following error -

  Message=exception: no description
  Source=C:\W\Framework\Notebooks\RabbitStreamsSSLConsumer.py
  StackTrace:
  File "C:\W\Framework\Notebooks\RabbitStreamsSSLConsumer.py", line 32, in consume (Current frame)
    loop.add_signal_handler(signal.SIGINT, lambda: asyncio.create_task(consumer.close()))
  File "C:\W\Framework\Notebooks\RabbitStreamsSSLConsumer.py", line 45, in <module>
    asyncio.run(consume())
NotImplementedError: 

I haven't changed anything in code. Could any one please help by pointing what I am missing?

**Comment by Gsantomaggio** [comment] 2023-11-10 08:31
It seems you want to use  SSL `RabbitStreamsSSLConsumer.py`. 
Can you please provide more info like:
- RabbitMQ version 
- Did you configure TLS?
- Can you provide the full `RabbitStreamsSSLConsumer.py` file? 
- Is the RabbitMQ stream plugin enabled?

**Comment by Utsavv** [comment] 2023-11-14 07:04
Hi,

Thank you for your reply and I am sorry for delayed reply. Given below are answers to the questions you asked -

RabbitMQ version - RabbitMQ 3.11.19
Did you configure TLS? - Yes.
Is the RabbitMQ stream plugin enabled? - Yes

Content - attached text file is the renamed .py file as .txt

[RabbitStreamsSSLConsumer.txt](https://github.com/qweeze/rstream/files/13345528/RabbitStreamsSSLConsumer.txt)

**Comment by Gsantomaggio** [comment] 2023-11-14 20:50
FYI: You are not using the TLS! the TLS port is 5551.

So the problem is during the close, right?
Can you please post the steps to reproduce the issue?

**Comment by Utsavv** [comment] 2023-11-15 04:35
Thanks for your input and time. I fixed that. However error is still coming at line loop.add_signal_handler(signal.SIGINT, lambda: asyncio.create_task(consumer.close())). Till that line I don't think RabbitMQ is getting connected.

**Comment by Utsavv** [comment] 2023-11-17 09:51
Thanks a lot for your help!

**Comment by DanielePalaia** [comment] 2024-01-05 10:11
Hello, I will close this issue as it is not relate to a bug to the client.

The examples are provided as a guidance for users to use the client.

@Utsavv if you solved the issue and you would like to open a PR with an example working for windows you are welcome!

**Closed by DanielePalaia** 2024-01-05 10:11 UTC
